# Site settings
title: HELFA SAFITRI
description:   '<p>Mahasiswa Sistem informasi TA 2014</p>
                <p>Fakultas : Sain dan Teknologi</p>
               <p>Universitas  Islam Negeri Sultan Syarif Kasim Riau</p>'
url: 'http://helfasafitri.github.io'
baseurl: '/helfasafitri.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'helfasafitri'
  email: helfasafitri@gmail.com
  twitter_username: helfha
  facebook_username: helfha syafitry
  github_username:  helfasafitri
  linkedin_username:  helfasafitri
  uin suska: http://uin-suska.ac.id/
  sif uin: http://sif.uin-suska.ac.id/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
