# Site settings
title: helfa safitri
description:   '<p> Mahasiswa di <a href="uin-suska.ac.id">Universitas Islam Negeri Sultan Syarif Kasim Riau</a></p>
                <p> program studi : sistem informasi </p>
               <p> fakultas : sain dan teknologi </p>'
url: 'http://helfasafitri.github.io'
baseurl: '/helfasafitri.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
<img src="/helfasafitri.github.io/images/profile.jpg" class="user-image" alt="My Profile Photo">

author:
  name: 'Mahasiswa Sistem Informasi Uin Suska Riau - Powered by Jekyll Uno'
  email: helfasafitri@gmail.com
  twitter_username: @helfha
  facebook_username: helfha syafitry
  github_username:  helfasafitri
  linkedin_username:  helfasafitri

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
